import type { KycApplicationRow } from "@/hooks/useKyc";

// ─── Mock KYC applications ────────────────────────────────────────────────────
// Replace this store with real API data once the backend is connected.

const INITIAL_APPLICATIONS: KycApplicationRow[] = [
  {
    id: "KYC-3001",
    userId: "U-0041",
    userName: "Chisomo Banda",
    userEmail: "chisomo.banda@email.com",
    userPhone: "+265 991 204 841",
    status: "PENDING",
    nationalIdNumber: "MW-NID-991204841",
    city: "Lilongwe",
    facialMatchScore: 91,
    ocrConfidence: 94,
    documentType: "NATIONAL_ID",
    reviewDecision: null,
    submittedAt: new Date(Date.now() - 2 * 60_000).toISOString(),       // 2 min ago
    reviewedAt: null,
  },
  {
    id: "KYC-3002",
    userId: "U-0082",
    userName: "Grace Mwale",
    userEmail: "grace.mwale@email.com",
    userPhone: "+265 888 410 822",
    status: "PENDING",
    nationalIdNumber: "MW-NID-888410822",
    city: "Blantyre",
    facialMatchScore: 88,
    ocrConfidence: 90,
    documentType: "NATIONAL_ID",
    reviewDecision: null,
    submittedAt: new Date(Date.now() - 18 * 60_000).toISOString(),      // 18 min ago
    reviewedAt: null,
  },
  {
    id: "KYC-3003",
    userId: "U-0017",
    userName: "Tadala Phiri",
    userEmail: "tadala.phiri@email.com",
    userPhone: "+265 999 351 017",
    status: "PENDING",
    nationalIdNumber: "MW-NID-999351017",
    city: "Mzuzu",
    facialMatchScore: 79,
    ocrConfidence: 72,
    documentType: "PASSPORT",
    reviewDecision: null,
    submittedAt: new Date(Date.now() - 34 * 60_000).toISOString(),      // 34 min ago
    reviewedAt: null,
  },
  {
    id: "KYC-3004",
    userId: "U-0055",
    userName: "Peter Gondwe",
    userEmail: "peter.gondwe@email.com",
    userPhone: "+265 888 602 055",
    status: "PENDING",
    nationalIdNumber: "MW-NID-888602055",
    city: "Lilongwe",
    facialMatchScore: 84,
    ocrConfidence: 88,
    documentType: "NATIONAL_ID",
    reviewDecision: null,
    submittedAt: new Date(Date.now() - 62 * 60_000).toISOString(),      // 1 hr ago
    reviewedAt: null,
  },
  {
    id: "KYC-3005",
    userId: "U-0093",
    userName: "Mercy Chirwa",
    userEmail: "mercy.chirwa@email.com",
    userPhone: "+265 991 706 093",
    status: "PENDING",
    nationalIdNumber: "MW-NID-991706093",
    city: "Blantyre",
    facialMatchScore: 65,
    ocrConfidence: 61,
    documentType: "NATIONAL_ID",
    reviewDecision: null,
    submittedAt: new Date(Date.now() - 2 * 3_600_000).toISOString(),    // 2 hr ago
    reviewedAt: null,
  },
  {
    id: "KYC-3006",
    userId: "U-0118",
    userName: "Madalitso Mbewe",
    userEmail: "madalitso.mbewe@email.com",
    userPhone: "+265 999 118 204",
    status: "APPROVED",
    nationalIdNumber: "MW-NID-999118204",
    city: "Lilongwe",
    facialMatchScore: 96,
    ocrConfidence: 97,
    documentType: "NATIONAL_ID",
    reviewDecision: "APPROVED",
    submittedAt: new Date(Date.now() - 5 * 3_600_000).toISOString(),
    reviewedAt: new Date(Date.now() - 4 * 3_600_000).toISOString(),
  },
  {
    id: "KYC-3007",
    userId: "U-0063",
    userName: "Kondwani Tembo",
    userEmail: "kondwani.tembo@email.com",
    userPhone: "+265 888 063 917",
    status: "APPROVED",
    nationalIdNumber: "MW-NID-888063917",
    city: "Zomba",
    facialMatchScore: 93,
    ocrConfidence: 95,
    documentType: "PASSPORT",
    reviewDecision: "APPROVED",
    submittedAt: new Date(Date.now() - 8 * 3_600_000).toISOString(),
    reviewedAt: new Date(Date.now() - 7 * 3_600_000).toISOString(),
  },
  {
    id: "KYC-3008",
    userId: "U-0079",
    userName: "Takondwa Nkhonjera",
    userEmail: "takondwa.nkhonjera@email.com",
    userPhone: "+265 991 079 445",
    status: "APPROVED",
    nationalIdNumber: "MW-NID-991079445",
    city: "Blantyre",
    facialMatchScore: 89,
    ocrConfidence: 91,
    documentType: "NATIONAL_ID",
    reviewDecision: "APPROVED",
    submittedAt: new Date(Date.now() - 24 * 3_600_000).toISOString(),
    reviewedAt: new Date(Date.now() - 23 * 3_600_000).toISOString(),
  },
  {
    id: "KYC-3009",
    userId: "U-0034",
    userName: "Pemphero Kachingwe",
    userEmail: "pemphero.kachingwe@email.com",
    userPhone: "+265 888 034 228",
    status: "APPROVED",
    nationalIdNumber: "MW-NID-888034228",
    city: "Lilongwe",
    facialMatchScore: 87,
    ocrConfidence: 89,
    documentType: "NATIONAL_ID",
    reviewDecision: "APPROVED",
    submittedAt: new Date(Date.now() - 30 * 3_600_000).toISOString(),
    reviewedAt: new Date(Date.now() - 29 * 3_600_000).toISOString(),
  },
  {
    id: "KYC-3010",
    userId: "U-0112",
    userName: "Lusungu Kamwendo",
    userEmail: "lusungu.kamwendo@email.com",
    userPhone: "+265 999 112 331",
    status: "APPROVED",
    nationalIdNumber: "MW-NID-999112331",
    city: "Mzuzu",
    facialMatchScore: 94,
    ocrConfidence: 92,
    documentType: "DRIVERS_LICENSE",
    reviewDecision: "APPROVED",
    submittedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
    reviewedAt: new Date(Date.now() - 2 * 86_400_000 + 3_600_000).toISOString(),
  },
  {
    id: "KYC-3011",
    userId: "U-0027",
    userName: "Blessings Msukwa",
    userEmail: "blessings.msukwa@email.com",
    userPhone: "+265 888 027 119",
    status: "REJECTED",
    nationalIdNumber: null,
    city: "Blantyre",
    facialMatchScore: 42,
    ocrConfidence: 38,
    documentType: "NATIONAL_ID",
    reviewDecision: "REJECTED",
    submittedAt: new Date(Date.now() - 12 * 3_600_000).toISOString(),
    reviewedAt: new Date(Date.now() - 11 * 3_600_000).toISOString(),
  },
  {
    id: "KYC-3012",
    userId: "U-0048",
    userName: "Rejoice Phwemba",
    userEmail: "rejoice.phwemba@email.com",
    userPhone: "+265 991 048 772",
    status: "REJECTED",
    nationalIdNumber: null,
    city: "Lilongwe",
    facialMatchScore: 55,
    ocrConfidence: 48,
    documentType: "PASSPORT",
    reviewDecision: "REJECTED",
    submittedAt: new Date(Date.now() - 3 * 86_400_000).toISOString(),
    reviewedAt: new Date(Date.now() - 3 * 86_400_000 + 2 * 3_600_000).toISOString(),
  },
  {
    id: "KYC-3013",
    userId: "U-0091",
    userName: "Wongani Nyirongo",
    userEmail: "wongani.nyirongo@email.com",
    userPhone: "+265 888 091 564",
    status: "REJECTED",
    nationalIdNumber: null,
    city: "Mzuzu",
    facialMatchScore: 31,
    ocrConfidence: 44,
    documentType: "NATIONAL_ID",
    reviewDecision: "REJECTED",
    submittedAt: new Date(Date.now() - 5 * 86_400_000).toISOString(),
    reviewedAt: new Date(Date.now() - 5 * 86_400_000 + 3_600_000).toISOString(),
  },
  {
    id: "KYC-3014",
    userId: "U-0066",
    userName: "Salome Dziwiri",
    userEmail: "salome.dziwiri@email.com",
    userPhone: "+265 999 066 883",
    status: "PENDING",
    nationalIdNumber: "MW-NID-999066883",
    city: "Zomba",
    facialMatchScore: 73,
    ocrConfidence: 68,
    documentType: "NATIONAL_ID",
    reviewDecision: null,
    submittedAt: new Date(Date.now() - 3 * 3_600_000).toISOString(),
    reviewedAt: null,
  },
  {
    id: "KYC-3015",
    userId: "U-0103",
    userName: "Innocent Banda",
    userEmail: "innocent.banda@email.com",
    userPhone: "+265 888 103 290",
    status: "PENDING",
    nationalIdNumber: "MW-NID-888103290",
    city: "Lilongwe",
    facialMatchScore: 82,
    ocrConfidence: 85,
    documentType: "DRIVERS_LICENSE",
    reviewDecision: null,
    submittedAt: new Date(Date.now() - 4 * 3_600_000).toISOString(),
    reviewedAt: null,
  },
  {
    id: "KYC-3016",
    userId: "U-0075",
    userName: "Agness Chimwala",
    userEmail: "agness.chimwala@email.com",
    userPhone: "+265 991 075 407",
    status: "APPROVED",
    nationalIdNumber: "MW-NID-991075407",
    city: "Blantyre",
    facialMatchScore: 90,
    ocrConfidence: 93,
    documentType: "NATIONAL_ID",
    reviewDecision: "APPROVED",
    submittedAt: new Date(Date.now() - 48 * 3_600_000).toISOString(),
    reviewedAt: new Date(Date.now() - 47 * 3_600_000).toISOString(),
  },
  {
    id: "KYC-3017",
    userId: "U-0022",
    userName: "Frank Mwaungulu",
    userEmail: "frank.mwaungulu@email.com",
    userPhone: "+265 888 022 611",
    status: "PENDING",
    nationalIdNumber: "MW-NID-888022611",
    city: "Mzuzu",
    facialMatchScore: 77,
    ocrConfidence: 80,
    documentType: "PASSPORT",
    reviewDecision: null,
    submittedAt: new Date(Date.now() - 6 * 3_600_000).toISOString(),
    reviewedAt: null,
  },
  {
    id: "KYC-3018",
    userId: "U-0137",
    userName: "Chikondi Matewere",
    userEmail: "chikondi.matewere@email.com",
    userPhone: "+265 999 137 055",
    status: "APPROVED",
    nationalIdNumber: "MW-NID-999137055",
    city: "Lilongwe",
    facialMatchScore: 92,
    ocrConfidence: 96,
    documentType: "NATIONAL_ID",
    reviewDecision: "APPROVED",
    submittedAt: new Date(Date.now() - 72 * 3_600_000).toISOString(),
    reviewedAt: new Date(Date.now() - 71 * 3_600_000).toISOString(),
  },
  {
    id: "KYC-3019",
    userId: "U-0059",
    userName: "Vitumbiko Kapito",
    userEmail: "vitumbiko.kapito@email.com",
    userPhone: "+265 888 059 738",
    status: "PENDING",
    nationalIdNumber: "MW-NID-888059738",
    city: "Blantyre",
    facialMatchScore: 58,
    ocrConfidence: 63,
    documentType: "NATIONAL_ID",
    reviewDecision: null,
    submittedAt: new Date(Date.now() - 9 * 3_600_000).toISOString(),
    reviewedAt: null,
  },
  {
    id: "KYC-3020",
    userId: "U-0088",
    userName: "Liness Chisale",
    userEmail: "liness.chisale@email.com",
    userPhone: "+265 991 088 174",
    status: "REJECTED",
    nationalIdNumber: null,
    city: "Zomba",
    facialMatchScore: 49,
    ocrConfidence: 52,
    documentType: "DRIVERS_LICENSE",
    reviewDecision: "REJECTED",
    submittedAt: new Date(Date.now() - 7 * 86_400_000).toISOString(),
    reviewedAt: new Date(Date.now() - 7 * 86_400_000 + 2 * 3_600_000).toISOString(),
  },
];

// ─── Simple module-level store ────────────────────────────────────────────────

let _applications: KycApplicationRow[] = [...INITIAL_APPLICATIONS];
const _listeners = new Set<() => void>();

function notify() {
  _listeners.forEach((l) => l());
}

export const kycStore = {
  getAll(): KycApplicationRow[] {
    return _applications;
  },
  getById(id: string): KycApplicationRow | undefined {
    return _applications.find((a) => a.id === id);
  },
  update(id: string, patch: Partial<KycApplicationRow>) {
    _applications = _applications.map((a) => (a.id === id ? { ...a, ...patch } : a));
    notify();
  },
  subscribe(listener: () => void): () => void {
    _listeners.add(listener);
    return () => _listeners.delete(listener);
  },
};
