/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalsRouteImport } from './routes/withdrawals'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MobileThemesRouteImport } from './routes/mobile-themes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as UsersUserIdRouteImport } from './routes/users_.$userId'
import { Route as SupportTicketIdRouteImport } from './routes/support_.$ticketId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as KycApplicationIdRouteImport } from './routes/kyc_.$applicationId'
import { Route as BrokersBrokerIdRouteImport } from './routes/brokers_.$brokerId'

const WithdrawalsRoute = WithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileThemesRoute = MobileThemesRouteImport.update({
  id: '/mobile-themes',
  path: '/mobile-themes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users_/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketIdRoute = SupportTicketIdRouteImport.update({
  id: '/support_/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const KycApplicationIdRoute = KycApplicationIdRouteImport.update({
  id: '/kyc_/$applicationId',
  path: '/kyc/$applicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersBrokerIdRoute = BrokersBrokerIdRouteImport.update({
  id: '/brokers_/$brokerId',
  path: '/brokers/$brokerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/audit': typeof AuditRoute
  '/brokers': typeof BrokersRoute
  '/coming-soon': typeof ComingSoonRoute
  '/errors': typeof ErrorsRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/mobile-themes': typeof MobileThemesRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/treasury': typeof TreasuryRoute
  '/users': typeof UsersRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/kyc/$applicationId': typeof KycApplicationIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/audit': typeof AuditRoute
  '/brokers': typeof BrokersRoute
  '/coming-soon': typeof ComingSoonRoute
  '/errors': typeof ErrorsRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/mobile-themes': typeof MobileThemesRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/treasury': typeof TreasuryRoute
  '/users': typeof UsersRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/kyc/$applicationId': typeof KycApplicationIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/audit': typeof AuditRoute
  '/brokers': typeof BrokersRoute
  '/coming-soon': typeof ComingSoonRoute
  '/errors': typeof ErrorsRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/mobile-themes': typeof MobileThemesRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/treasury': typeof TreasuryRoute
  '/users': typeof UsersRoute
  '/withdrawals': typeof WithdrawalsRoute
  '/brokers_/$brokerId': typeof BrokersBrokerIdRoute
  '/kyc_/$applicationId': typeof KycApplicationIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/support_/$ticketId': typeof SupportTicketIdRoute
  '/users_/$userId': typeof UsersUserIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/audit'
    | '/brokers'
    | '/coming-soon'
    | '/errors'
    | '/kyc'
    | '/login'
    | '/mobile-themes'
    | '/news'
    | '/notifications'
    | '/orders'
    | '/settings'
    | '/support'
    | '/treasury'
    | '/users'
    | '/withdrawals'
    | '/brokers/$brokerId'
    | '/kyc/$applicationId'
    | '/orders/$orderId'
    | '/support/$ticketId'
    | '/users/$userId'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/audit'
    | '/brokers'
    | '/coming-soon'
    | '/errors'
    | '/kyc'
    | '/login'
    | '/mobile-themes'
    | '/news'
    | '/notifications'
    | '/settings'
    | '/support'
    | '/treasury'
    | '/users'
    | '/withdrawals'
    | '/brokers/$brokerId'
    | '/kyc/$applicationId'
    | '/orders/$orderId'
    | '/support/$ticketId'
    | '/users/$userId'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/audit'
    | '/brokers'
    | '/coming-soon'
    | '/errors'
    | '/kyc'
    | '/login'
    | '/mobile-themes'
    | '/news'
    | '/notifications'
    | '/orders'
    | '/settings'
    | '/support'
    | '/treasury'
    | '/users'
    | '/withdrawals'
    | '/brokers_/$brokerId'
    | '/kyc_/$applicationId'
    | '/orders/$orderId'
    | '/support_/$ticketId'
    | '/users_/$userId'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  AuditRoute: typeof AuditRoute
  BrokersRoute: typeof BrokersRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ErrorsRoute: typeof ErrorsRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  MobileThemesRoute: typeof MobileThemesRoute
  NewsRoute: typeof NewsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TreasuryRoute: typeof TreasuryRoute
  UsersRoute: typeof UsersRoute
  WithdrawalsRoute: typeof WithdrawalsRoute
  BrokersBrokerIdRoute: typeof BrokersBrokerIdRoute
  KycApplicationIdRoute: typeof KycApplicationIdRoute
  SupportTicketIdRoute: typeof SupportTicketIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawals': {
      id: '/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof WithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-themes': {
      id: '/mobile-themes'
      path: '/mobile-themes'
      fullPath: '/mobile-themes'
      preLoaderRoute: typeof MobileThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/users_/$userId': {
      id: '/users_/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support_/$ticketId': {
      id: '/support_/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof SupportTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/kyc_/$applicationId': {
      id: '/kyc_/$applicationId'
      path: '/kyc/$applicationId'
      fullPath: '/kyc/$applicationId'
      preLoaderRoute: typeof KycApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers_/$brokerId': {
      id: '/brokers_/$brokerId'
      path: '/brokers/$brokerId'
      fullPath: '/brokers/$brokerId'
      preLoaderRoute: typeof BrokersBrokerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  AuditRoute: AuditRoute,
  BrokersRoute: BrokersRoute,
  ComingSoonRoute: ComingSoonRoute,
  ErrorsRoute: ErrorsRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  MobileThemesRoute: MobileThemesRoute,
  NewsRoute: NewsRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TreasuryRoute: TreasuryRoute,
  UsersRoute: UsersRoute,
  WithdrawalsRoute: WithdrawalsRoute,
  BrokersBrokerIdRoute: BrokersBrokerIdRoute,
  KycApplicationIdRoute: KycApplicationIdRoute,
  SupportTicketIdRoute: SupportTicketIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
